version: '3.9'
services:
  apidb:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: base
  api:
    build: FinanceProjectApi/
    ports:
      - 8000:8000
#    command: python manage.py runserver 0.0.0.0:8000
#    command: ["./wait-for-it.sh", "db:5432", "--", "python", "manage.py", "runserver", "0.0.0.0:8000"]
#    command: >
#      sh -c "./wait-for-it.sh apidb:5432 &&
#      python manage.py migrate &&
#      python manage.py shell -c "from django.contrib.auth.models import User; User.objects.create_superuser('admin', 'admin@example.com', 'admin')" &&
#      python manage.py runserver 0.0.0.0:8000"
    command: >
      sh -c "./wait-for-it.sh apidb:5432 &&
      ./start.sh"
    depends_on:
      - apidb
  bot:
    build: FinanceProjectBot/
    depends_on:
      - api
      - apidb


