version: '3.9'
services:
  api:
    build: FinanceProjectApi/
    environment:
      DB_HOST: apidb
      DB_NAME: base
      DB_USER: user
      DB_PASSWORD: password
    ports:
      - 8000:8000
    command: python manage.py runserver 0.0.0.0:8000
#    command: >
#      sh -c "python manage.py migrate &&
#             python manage.py runserver 0.0.0.0:8000"
#    python manage.py runserver 0.0.0.0:8000
#      - python manage.py migrate
#      - python manage.py shell -c "from django.contrib.auth.models import User; User.objects.create_superuser('admin', 'admin@example.com', 'admin')"
#      - gunicorn -b 0.0.0.0:8000 config.wsgi --log-file -
#      - python manage.py runserver 0.0.0.0:8000
    depends_on:
      - apidb
#    networks:
#      - finance-network
  bot:
    build: FinanceProjectBot/
    depends_on:
      - api
      - apidb
  apidb:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: base


