# Generated by Django 3.2.9 on 2021-11-25 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211125_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operations',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='main.categories', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='operations',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
