# Generated by Django 3.2.9 on 2021-11-28 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_categories_cat_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='expense',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='income',
        ),
    ]
