# Generated by Django 3.2.9 on 2021-12-02 13:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20211128_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Category name')),
                ('cat_type', models.CharField(choices=[('EXP', 'Expense'), ('INC', 'Income')], default='EXP', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('amount', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Value less than zero')], verbose_name='Величина')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='main.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Operation',
                'verbose_name_plural': 'Operations',
                'ordering': ('-created_at',),
            },
        ),
        migrations.RemoveField(
            model_name='operations',
            name='category',
        ),
        migrations.RemoveField(
            model_name='operations',
            name='user',
        ),
        migrations.AlterField(
            model_name='advuser',
            name='is_activated',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Activated?'),
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='Operations',
        ),
        migrations.AddField(
            model_name='operation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
