# Generated by Django 3.2.9 on 2021-12-07 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20211207_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='user',
        ),
    ]
