# Generated by Django 3.2.9 on 2021-12-07 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_operation_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='api_user',
            new_name='user',
        ),
    ]
