# Generated by Django 3.2.9 on 2021-12-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_operation_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apiuser',
            options={'ordering': ('user_id',), 'verbose_name': 'Api User', 'verbose_name_plural': 'Api Users'},
        ),
        migrations.AddField(
            model_name='apiuser',
            name='user_id',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
