# Generated by Django 3.2.9 on 2021-12-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20211207_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiuser',
            name='user_id',
            field=models.PositiveBigIntegerField(),
        ),
    ]
