# Generated by Django 3.2.9 on 2021-12-08 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_apiuser_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apiuser',
            options={'ordering': ('chat_id',), 'verbose_name': 'API User', 'verbose_name_plural': 'API Users'},
        ),
        migrations.RenameField(
            model_name='apiuser',
            old_name='user_id',
            new_name='chat_id',
        ),
        migrations.RenameField(
            model_name='apiuser',
            old_name='username',
            new_name='first_name',
        ),
    ]
