# Generated by Django 3.2.9 on 2021-12-12 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20211208_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active?'),
        ),
    ]
