# Generated by Django 3.2.9 on 2021-12-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_operation_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiuser',
            name='chat_id',
            field=models.PositiveBigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='apiuser',
            name='first_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True, verbose_name='User name'),
        ),
    ]
