# Generated by Django 3.2.9 on 2021-12-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20211212_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiuser',
            name='last_name',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True, verbose_name='Last name'),
        ),
        migrations.AddField(
            model_name='apiuser',
            name='username',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True, verbose_name='User name'),
        ),
        migrations.AlterField(
            model_name='apiuser',
            name='first_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='First name'),
        ),
    ]
