# Generated by Django 3.2.9 on 2021-12-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20211219_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiuser',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True, verbose_name='Created'),
        ),
        migrations.AddField(
            model_name='apiuser',
            name='updated_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True, verbose_name='Updated'),
        ),
    ]
