# Generated by Django 3.2.9 on 2021-12-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20211224_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiuser',
            name='date_filter_end',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Date filter end'),
        ),
        migrations.AlterField(
            model_name='apiuser',
            name='date_filter_start',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Date filter start'),
        ),
    ]
