# Generated by Django 3.2.9 on 2021-12-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20211224_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiuser',
            name='date_filter_end',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Date filter end'),
        ),
        migrations.AddField(
            model_name='apiuser',
            name='date_filter_start',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Date filter start'),
        ),
        migrations.AddField(
            model_name='apiuser',
            name='pin_message_id',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Pinned message id'),
        ),
    ]
